#!/usr/bin/env python3
"""
setup.py — MPV Auto-Deploy System

One command to rule them all. Detects your OS, installs dependencies,
fetches scripts from their upstream sources, and deploys everything
to the right place.

Usage:
    mpv-config                       # Full install (interactive, after install.sh)
    mpv-config --install             # Full install
    mpv-config --update              # Update scripts only
    mpv-config --rollback            # Restore latest backup
    mpv-config --rollback <backup_dir>  # Restore specific backup
    mpv-config --uninstall           # Remove deployed files
    mpv-config --verify              # Verify current install
    mpv-config --status              # Show install status
    mpv-config --migrate-from-old    # Preserve old overrides into mpv.conf.user
    mpv-config --dry-run             # Preview without changes
    # Manual fallback:
    python setup.py [flags]
"""

import sys
sys.dont_write_bytecode = True

import argparse
import json
import os
import re
import shutil
import tempfile
import uuid

# Ensure we can import the deploy package from this script's directory
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)


# ── Import deploy modules (ui has built-in non-rich fallback) ───
from deploy import ui
from deploy.audit_log import AuditLog
from deploy.deployer import (
    _patch_mpv_conf,
    _resolve_mpv_profile,
    backup_existing,
    deploy,
    list_backups,
    rollback_config,
)
from deploy.deployer import (
    _remove_path as remove_path_safe,
)
from deploy.detector import detect
from deploy.fetcher import fetch_all
from deploy.installer import install_deps, uninstall_deps
from deploy.planner import (
    build_install_plan,
    build_uninstall_plan,
    build_update_plan,
    confirm_plan,
    display_plan,
)
from deploy.registry import (
    MPV_EXPERIENCE_PROFILES,
    MPV_PROFILE_DEFAULT,
    SCRIPTS,
    SHADERS,
)
from deploy.verifier import verify
from deploy import transaction as tx

LATEST_BACKUP_SENTINEL = "__latest__"
DEFAULT_INSTALL_DIR = os.path.expanduser("~/.mpv-deploy")
DEFAULT_LAUNCHER = os.path.expanduser("~/.local/bin/mpv-config")
MENU_MAX_OPTION = 8


def _is_dry_run(args):
    return bool(getattr(args, "dry_run", False))


def _safe_realpath(path):
    return tx.canonical(path)


def _ensure_distinct_paths(*paths):
    tx.assert_disjoint(*paths)


def _operation_lock(config_dir):
    return tx.operation_lock(config_dir)


def _audit_log_for(env):
    """Return an AuditLog instance pointing at the config dir's log file."""
    log_path = os.path.join(env.config_dir, ".audit-log.json")
    return AuditLog(log_path)


def _parse_mpv_conf(content):
    """Parse mpv.conf style content into {section: {key: value}}."""
    entries = {}
    current_section = None
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("[") and stripped.endswith("]"):
            current_section = stripped[1:-1]
            continue
        if "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        entries.setdefault(current_section, {})[key.strip()] = value.strip()
    return entries


def _extract_overrides(content, defaults):
    overrides = {}
    order = []
    current_section = None
    placeholder_pattern = re.compile(r"\{\{[A-Z0-9_]+\}\}")

    def _ensure_section(section):
        if section not in overrides:
            overrides[section] = []
            order.append(section)

    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("[") and stripped.endswith("]"):
            current_section = stripped[1:-1]
            continue
        if "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        key = key.strip()
        value = value.strip()
        if key.lower() == "include":
            continue
        default_value = defaults.get(current_section, {}).get(key)
        if default_value is None:
            keep = True
        else:
            default_value = default_value.strip()
            if placeholder_pattern.search(default_value):
                keep = False
            else:
                keep = value != default_value
        if keep:
            _ensure_section(current_section)
            overrides[current_section].append((key, value))

    return order, overrides


def _write_mpv_conf_user(dest_path, order, overrides):
    lines = [
        "# mpv.conf.user - preserved user overrides",
        "# Generated by: mpv-config --migrate-from-old",
        "",
    ]
    has_entries = any(bool(overrides.get(s)) for s in order)
    if not has_entries:
        lines.append("# No overrides detected.")
    else:
        for section in order:
            entries = overrides.get(section, [])
            if not entries:
                continue
            if section:
                lines.append(f"[{section}]")
            for key, value in entries:
                lines.append(f"{key} = {value}")
            lines.append("")
    with open(dest_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).rstrip() + "\n")


def _migrate_input_conf(input_conf_path, audit_log=None):
    """Update stale system keybindings in input.conf (e.g. F8 night mode, mouse right-click pause)
    while preserving all custom user keybindings and comments."""
    if not os.path.isfile(input_conf_path):
        return False

    with open(input_conf_path, "r", encoding="utf-8") as f:
        content = f.read()

    updated_content = content

    # 1. Migrate F8 night mode binding
    new_f8_binding = (
        'F8 cycle-values af '
        '"lavfi=[dynaudnorm=f=500:g=15:p=0.95:m=10],lavfi=[alimiter=limit=0.9:level=false]" ""'
    )

    pattern_f8 = re.compile(
        r'^[ \t]*F8[ \t]+cycle-values[ \t]+af[ \t]+["\']lavfi=\[dynaudnorm=[^"\']*\]["\'][ \t]+["\']["\'][ \t]*$',
        re.MULTILINE,
    )

    if pattern_f8.search(updated_content):
        updated_content = pattern_f8.sub(new_f8_binding, updated_content)
        old_comment = (
            "# F8: (جديد) تفعيل/تعطيل توحيد مستوى الصوت (Stable Volume / Night Mode)\n"
            "# مفيد جداً في الأنمي والأفلام التي يكون فيها صوت الحوار منخفضاً والمؤثرات عالية"
        )
        new_comment = (
            "# F8: تفعيل/تعطيل توحيد مستوى الصوت (Stable Volume / Night Mode)\n"
            "# مفيد جداً في الأنمي والأفلام التي يكون فيها صوت الحوار منخفضاً والمؤثرات عالية\n"
            '# f=500   : نافذة تحليل أطول = استجابة أهدأ، لا "تنفس" مسموع\n'
            "# g=15    : أقصى رفع 15dB بدلاً من 31 — لا يضخم هسهسة الخلفية\n"
            "# p=0.95  : هدف قمة قريب من المستوى الكامل، لا ضغط حاد نحو 50%\n"
            "# m=10    : سقف لمعدل تغير الكسب لكل إطار — يقتل ضخّ الكسب المفاجئ\n"
            "# alimiter: جدار حماية نهائي يمنع القص الرقمي عند رفع volume فوق 100%"
        )
        if old_comment in updated_content:
            updated_content = updated_content.replace(old_comment, new_comment)

    # 2. Migrate / ensure MBTN_RIGHT and MBTN_RIGHT_DBL mouse bindings
    mbtn_right_match = re.search(
        r'^[ \t]*MBTN_RIGHT[ \t]+([^\r\n#]+)', updated_content, re.MULTILINE
    )
    if mbtn_right_match:
        current_cmd = mbtn_right_match.group(1).strip()
        if current_cmd in ("context-menu", "show-text context-menu"):
            updated_content = re.sub(
                r'^[ \t]*MBTN_RIGHT[ \t]+[^\r\n#]+',
                "MBTN_RIGHT       cycle pause",
                updated_content,
                count=1,
                flags=re.MULTILINE,
            )
    else:
        # MBTN_RIGHT is absent -> append mouse bindings block cleanly
        mouse_block = (
            "\n# ── Mouse Bindings ── Restore classic right-click pause over native context menu\n"
            "MBTN_RIGHT       cycle pause\n"
            "MBTN_RIGHT_DBL   ignore\n"
        )
        updated_content = updated_content.rstrip() + "\n" + mouse_block

    # Check MBTN_RIGHT_DBL if MBTN_RIGHT was already present
    mbtn_right_dbl_match = re.search(
        r'^[ \t]*MBTN_RIGHT_DBL[ \t]+([^\r\n#]+)', updated_content, re.MULTILINE
    )
    if not mbtn_right_dbl_match:
        updated_content = re.sub(
            r'(^[ \t]*MBTN_RIGHT[ \t]+[^\r\n]+)',
            r"\1\nMBTN_RIGHT_DBL   ignore",
            updated_content,
            count=1,
            flags=re.MULTILINE,
        )
    elif mbtn_right_dbl_match.group(1).strip() in (
        "context-menu",
        "show-text context-menu",
    ):
        updated_content = re.sub(
            r'^[ \t]*MBTN_RIGHT_DBL[ \t]+[^\r\n#]+',
            "MBTN_RIGHT_DBL   ignore",
            updated_content,
            count=1,
            flags=re.MULTILINE,
        )

    # 3. Clean up manual clipboard loadfile overrides and migrate to smart_paste
    updated_content = re.sub(
        r'^[ \t]*Ctrl\+(?:Shift\+)?[vV][ \t]+loadfile[^\r\n]*\r?\n?',
        '',
        updated_content,
        flags=re.MULTILINE,
    )
    ctrl_v_match = re.search(
        r'^[ \t]*Ctrl\+v[ \t]+([^\r\n#]+)', updated_content, re.IGNORECASE | re.MULTILINE
    )
    smart_clipboard_block = (
        "\n# Instant play from clipboard (with automatic URL normalization & instant OSD)\n"
        "Ctrl+v           script-binding smart_paste/paste-to-open\n"
        "Ctrl+V           script-binding smart_paste/paste-to-open\n"
        "Ctrl+Shift+v     script-binding smart_paste/paste-to-playlist\n"
        "Ctrl+Shift+V     script-binding smart_paste/paste-to-playlist\n"
    )
    if not ctrl_v_match:
        updated_content = updated_content.rstrip() + "\n" + smart_clipboard_block
    elif "smart_paste" not in ctrl_v_match.group(1):
        updated_content = re.sub(
            r'^[ \t]*Ctrl\+(?:Shift\+)?[vV][ \t]+[^\r\n]+\r?\n?',
            '',
            updated_content,
            flags=re.MULTILINE,
        )
        updated_content = updated_content.rstrip() + "\n" + smart_clipboard_block

    # 4. Migrate / ensure Arabic bilingual twin keybindings
    updated_content = re.sub(
        r'^[ \t]*Ctrl\+(?:Shift\+)?(?:ر|Ø±)[ \t]+loadfile[^\r\n]*\r?\n?',
        '',
        updated_content,
        flags=re.MULTILINE,
    )
    if not re.search(r'^[ \t]*ا[ \t]+script-binding', updated_content, re.MULTILINE):
        arabic_bindings = (
            "\n# ─── Arabic Bilingual Twin Bindings (Arabic 101/102 Layout) ───\n"
            "# History (memo) — ا = h (History)\n"
            "ا        script-binding memo-history\n\n"
            "# SponsorBlock voting — ﻻ = B (Upvote), Shift+ﻻ / ﻵ = Shift+B (Downvote)\n"
            "ﻻ        script-binding sponsorblock_upvote\n"
            "Shift+ﻻ  script-binding sponsorblock_downvote\n"
            "ﻵ        script-binding sponsorblock_downvote\n\n"
            "# SponsorBlock segment marking / submission — ل = g, Shift+ل / إ = G\n"
            "ل        script-binding sponsorblock_set_segment\n"
            "Shift+ل  script-binding sponsorblock_submit_segment\n"
            "إ        script-binding sponsorblock_submit_segment\n\n"
            "# Explicit Latin bindings for SponsorBlock segment marking\n"
            "g        script-binding sponsorblock_set_segment\n"
            "G        script-binding sponsorblock_submit_segment\n\n"
            "# Subtitle sync (autosubsync) — ى = n (syNc)\n"
            "ى        script-binding autosubsync-menu\n\n"
            "# Instant play from clipboard — Ctrl+ر = Ctrl+v\n"
            "Ctrl+ر           script-binding smart_paste/paste-to-open\n"
            "Ctrl+Shift+ر     script-binding smart_paste/paste-to-playlist\n"
        )
        updated_content = updated_content.rstrip() + "\n" + arabic_bindings
    else:
        # Upgrade any existing raw loadfile / legacy / mojibake Arabic clipboard bindings
        ctrl_ar_match = re.search(r'^[ \t]*Ctrl\+(?:ر|Ø±)[ \t]+([^\r\n#]+)', updated_content, re.MULTILINE)
        if not ctrl_ar_match or "smart_paste" not in ctrl_ar_match.group(1):
            updated_content = re.sub(
                r'^[ \t]*Ctrl\+(?:Shift\+)?(?:ر|Ø±)[ \t]+[^\r\n]+\r?\n?',
                '',
                updated_content,
                flags=re.MULTILINE,
            )
            updated_content = updated_content.rstrip() + (
                "\n# Instant play from clipboard — Ctrl+ر = Ctrl+v\n"
                "Ctrl+ر           script-binding smart_paste/paste-to-open\n"
                "Ctrl+Shift+ر     script-binding smart_paste/paste-to-playlist\n"
            )

    if updated_content != content:
        with open(input_conf_path, "w", encoding="utf-8") as f:
            f.write(updated_content)
        if audit_log:
            audit_log.record_file(
                input_conf_path,
                "modify",
                "ok",
                "migrated input.conf bindings (F8, mouse, clipboard, arabic)",
            )
        return True

    return False


def _require_complete_fetch(results):
    expected = [entry["name"] for entry in SCRIPTS] + [SHADERS["name"]]
    names = [result.get("name") for result in results]
    if (len(names) != len(expected) or set(names) != set(expected)
            or any(result.get("status") != "ok" for result in results)):
        raise RuntimeError("Fetch was incomplete; no live configuration was replaced")


def cmd_install(args):
    """Fail-closed fetch, dependencies, recoverable deployment, then verification."""
    ui.banner()
    env = detect()
    plan = build_install_plan(env)
    display_plan(plan, "Installation Plan")
    if _is_dry_run(args):
        ui.info("[DRY RUN] No downloads, installs, audit writes, or replacements.")
        return
    if _is_interactive_session() and not confirm_plan(plan, "installation"):
        ui.warn("Installation cancelled by user.")
        return
    config_dir = tx.config_path(env.config_dir)
    tx.assert_disjoint(config_dir, SCRIPT_DIR)
    with _operation_lock(config_dir):
        parent = os.path.dirname(config_dir)
        with tempfile.TemporaryDirectory(prefix=".mpv-install-stage-", dir=parent) as staging:
            # Download first: a failed fetch must not install any dependencies.
            fetch_results, lockfile = fetch_all(SCRIPTS, SHADERS, staging)
            ui.summary(fetch_results)
            _require_complete_fetch(fetch_results)
            _validate_update_staging(staging)
            audit_log = _audit_log_for(env)
            audit_log.start_session("install", env)
            try:
                dep_results = install_deps(env, dry_run=False, audit_log=audit_log,
                                           mpv_version=args.mpv_version)
                ui.summary(dep_results)
                if any(result.get("status") == "failed" for result in dep_results):
                    raise RuntimeError("Dependency installation failed; configuration was not replaced")
                verify_results = []
                def check_install():
                    verify_results.extend(verify(config_dir, env))
                    if any(result.get("status") == "failed" for result in verify_results):
                        ui.summary(verify_results)
                        raise RuntimeError("Verification failed; restoring the previous configuration")
                deploy_results = deploy(
                    staging, env, SCRIPT_DIR, audit_log=audit_log,
                    mpv_profile=args.mpv_profile, anime_preset=args.anime_preset,
                    scaler_tier=args.scaler_tier, display_mode=args.display_mode,
                    dither_depth=args.dither_depth, lockfile=lockfile,
                    verify_callback=check_install,
                )
                if any(result.get("status") == "failed" for result in deploy_results):
                    raise RuntimeError("Deployment reported a failure")
                ui.summary(deploy_results + verify_results)
                audit_log.complete_session("completed")
                ui.panel(f"Deployment complete. Config: {config_dir}", title="Success", style="green")
            except BaseException as exc:
                audit_log.complete_session("cancelled" if isinstance(exc, KeyboardInterrupt) else "failed")
                raise


def cmd_migrate(args):
    """Generate a non-destructive migration candidate for explicit review.

    Existing configs, repeated directives, custom includes and personal user
    overrides are never silently parsed away or rewritten.
    """
    ui.banner()
    env = detect()
    config_dir = tx.config_path(env.config_dir)
    original = os.path.join(config_dir, "mpv.conf")
    if not os.path.isfile(original):
        raise FileNotFoundError(f"No existing mpv.conf at {original}")
    if _is_dry_run(args):
        ui.info("[DRY RUN] Would create uniquely named migration candidates; existing files stay untouched.")
        return
    tx.assert_disjoint(config_dir, SCRIPT_DIR)
    with _operation_lock(config_dir):
        audit_log = _audit_log_for(env)
        audit_log.start_session("migrate", env)
        candidate = tempfile.mkdtemp(prefix="migration-candidate-", dir=config_dir)
        try:
            shutil.copy2(original, os.path.join(candidate, "mpv.conf.original"), follow_symlinks=False)
            selected, defaults = _resolve_mpv_profile(env, args.mpv_profile)
            _patch_mpv_conf(os.path.join(SCRIPT_DIR, "config", "mpv.conf.template"),
                            os.path.join(candidate, "mpv.conf.new"), env, selected, defaults,
                            anime_preset=args.anime_preset, scaler_tier=args.scaler_tier,
                            display_mode=args.display_mode, dither_depth=args.dither_depth)
            with open(os.path.join(candidate, "REVIEW.txt"), "x", encoding="utf-8") as stream:
                stream.write("Candidates only: live mpv.conf and mpv.conf.user were NOT modified.\n"
                             "Compare the full original (including repeated options/includes) with mpv.conf.new.\n"
                             "Merge desired overrides into mpv.conf.user before replacing the live template.\n")
            audit_log.record_file(candidate, "create", "ok", "migration candidates only; review required")
            audit_log.complete_session("completed")
            ui.info(f"Review candidates in {candidate}; no live configuration was changed.")
        except BaseException:
            audit_log.complete_session("failed")
            raise


def ensure_mpv_conf_user(config_dir, audit_log=None):
    """Create an empty mpv.conf.user if absent so the template's trailing
    `include = "~~/mpv.conf.user"` never dangles on a fresh install.
    NEVER overwrites — existing user tweaks are the whole point of the file.
    Sanitizes any accidental recursive self-includes (e.g. include = "~~/mpv.conf.user")."""
    from deploy.deployer import ensure_mpv_conf_user as _deployer_ensure_mpv_conf_user
    return _deployer_ensure_mpv_conf_user(config_dir, audit_log=audit_log)


def _copy_tree_overlay(src, dst):
    tx.copy_overlay(src, dst)


def _validate_update_staging(staging_dir):
    tx.validate_staging(staging_dir)


def cmd_update(args):
    """Update only assets after complete fetch, keeping a recoverable backup."""
    ui.banner()
    env = detect()
    plan = build_update_plan(env)
    display_plan(plan, "Update Plan")
    if _is_dry_run(args):
        ui.info("[DRY RUN] No downloads, audit writes, staging, or replacements.")
        return
    if _is_interactive_session() and not confirm_plan(plan, "update"):
        ui.warn("Update cancelled by user.")
        return
    config_dir = tx.config_path(env.config_dir)
    tx.assert_disjoint(config_dir, SCRIPT_DIR)
    with _operation_lock(config_dir):
        parent = os.path.dirname(config_dir)
        with tempfile.TemporaryDirectory(prefix=".mpv-update-stage-", dir=parent) as staging:
            fetch_results, lockfile = fetch_all(SCRIPTS, SHADERS, staging)
            ui.summary(fetch_results)
            _require_complete_fetch(fetch_results)
            backup = tx.update_assets(config_dir, staging, SCRIPT_DIR, lockfile)
        # Logging starts only after the filesystem transaction succeeds.
        audit_log = _audit_log_for(env)
        audit_log.start_session("update", env)
        if backup:
            audit_log.record_backup(backup)
            ui.success(f"Previous configuration saved as: {backup}")
        audit_log.record_file(config_dir, "copy", "ok", "assets and manifest committed; personal configuration preserved")
        audit_log.complete_session("completed")
        ui.panel("Update complete. Personal configuration was preserved.", title="Success", style="green")


def cmd_sync_deps(args):
    """Sync MPV dependency suite (yt-dlp, ffmpeg-full, alass, ffsubsync)."""
    ui.banner()
    env = detect()
    if _is_dry_run(args):
        ui.info("[DRY RUN] Read-only preview only. Dependency sync skipped.")
        return
    audit_log = None
    try:
        with _operation_lock(env.config_dir):
            audit_log = _audit_log_for(env)
            audit_log.start_session("sync-deps", env)
            from deploy.installer import sync_dependencies
            results = sync_dependencies(env=env, dry_run=False, audit_log=audit_log)
            ui.summary(results)
            failed = any(r.get("status") == "failed" for r in results)
            if failed:
                ui.panel("Dependency synchronization completed with failures.", title="⚠️ Warning", style="yellow")
                audit_log.complete_session("completed_with_errors")
                sys.exit(1)
            ui.panel("Dependency synchronization complete!", title="✨ Success", style="green")
            audit_log.complete_session("completed")
    except Exception:
        try:
            if audit_log:
                audit_log.complete_session("failed")
        except Exception:
            pass
        raise


def cmd_verify(args):
    """Verify the selected install and return a failing CLI status on failure."""
    ui.banner()
    env = detect()
    results = verify(env.config_dir, env)
    ui.summary(results)
    if any(result.get("status") == "failed" for result in results):
        raise RuntimeError("Installation verification failed")


def cmd_status(args):
    """Show current install status vs available versions."""
    ui.banner()
    env = detect()

    lockfile_path = os.path.join(env.config_dir, ".deploy.lock.json")
    if not os.path.isfile(lockfile_path):
        ui.warn(
            "No deployment lockfile found. Run the curl installer first, then use 'mpv-config --install'."
        )
        return

    with open(lockfile_path, "r", encoding="utf-8") as f:
        lockfile = json.load(f)

    ui.header("Installed Scripts")

    scripts_data = lockfile.get("scripts", {})
    for name, info in scripts_data.items():
        version = info.get("version", info.get("source", "unknown"))
        date = info.get("fetched_at", "")[:10]
        ui.success(f"{name}: {version} (fetched {date})")

    # Also show audit log summary if available
    audit_log = _audit_log_for(env)
    sessions = audit_log.sessions()
    if sessions:
        last = sessions[-1]
        ui.header("Last Installer Session")
        ui.info(f"Operation : {last.get('operation', '?')}")
        ui.info(f"Status    : {last.get('status', '?')}")
        ui.info(f"Started   : {last.get('started_at', '?')}")
        ui.info(f"Completed : {last.get('completed_at', '?') or '(in progress)'}")
        pkg_safe = audit_log.get_packages_installed_by_us()
        if pkg_safe:
            ui.info(f"Installed by this tool (safe to remove): {', '.join(pkg_safe)}")

    ui.panel(
        f"Lockfile: {lockfile_path}\nConfig dir: {env.config_dir}",
        title="Environment Info",
        style="dim",
    )


def cmd_rollback(args):
    ui.banner()
    env = detect()
    requested = None if args.rollback == LATEST_BACKUP_SENTINEL else args.rollback
    if _is_dry_run(args):
        result = rollback_config(env.config_dir, backup_path=requested, dry_run=True)
        ui.summary([result])
        return
    if _is_interactive_session() and not ui.confirm("Restore backup and retain a safety snapshot?"):
        return
    with _operation_lock(env.config_dir):
        audit_log = _audit_log_for(env)
        audit_log.start_session("rollback", env)
        try:
            result = rollback_config(env.config_dir, backup_path=requested, audit_log=audit_log)
            ui.summary([result])
            if result.get("status") != "ok":
                raise RuntimeError("Rollback did not complete")
            audit_log.complete_session("completed")
        except BaseException:
            audit_log.complete_session("failed")
            raise


def _remove_deployed_files(
    env, purge_config=False, remove_backups=False, dry_run=False, audit_log=None
):
    results = []
    config_dir = env.config_dir

    managed_entries = [
        "scripts",
        "shaders",
        "fonts",
        "script-opts",
        "shader_cache",
        "chapters",
        "mpv.conf",
        "input.conf",
        ".deploy.lock.json",
        # NOTE: .audit-log.json is intentionally kept during partial uninstall
        # so it can still be consulted by future install / rollback operations.
        # It is only removed when purge_config=True wipes the entire config dir.
    ]

    if purge_config:
        if os.path.lexists(config_dir):
            is_symlink = os.path.islink(config_dir)
            kind = "symlink" if is_symlink else "config dir"
            if dry_run:
                ui.info(f"[DRY RUN] Would remove {kind}: {config_dir}")
                results.append(
                    {"name": "config_dir", "status": "skipped", "detail": "dry run"}
                )
            else:
                if is_symlink:
                    os.unlink(config_dir)
                else:
                    remove_path_safe(config_dir)
                ui.success(f"Removed {kind}: {config_dir}")
                results.append(
                    {"name": "config_dir", "status": "ok", "detail": f"removed {kind}"}
                )
                if audit_log:
                    audit_log.record_file(
                        config_dir, "delete", "ok", f"full {kind} removed"
                    )
        else:
            results.append(
                {"name": "config_dir", "status": "skipped", "detail": "not found"}
            )
    else:
        for name in managed_entries:
            path = os.path.join(config_dir, name)
            if not os.path.lexists(path):
                continue
            is_symlink = os.path.islink(path)
            kind = "symlink" if is_symlink else "file/dir"
            if dry_run:
                ui.info(f"[DRY RUN] Would remove {kind}: {path}")
                results.append({"name": name, "status": "skipped", "detail": "dry run"})
            else:
                if is_symlink:
                    os.unlink(path)
                else:
                    remove_path_safe(path)
                ui.success(f"Removed {kind}: {path}")
                results.append(
                    {"name": name, "status": "ok", "detail": f"removed {kind}"}
                )
                if audit_log:
                    audit_log.record_file(
                        path, "delete", "ok", f"removed {kind} by uninstall"
                    )

    if remove_backups:
        backups = list_backups(config_dir)
        if not backups:
            results.append(
                {"name": "backups", "status": "skipped", "detail": "none found"}
            )
        for backup in backups:
            if dry_run:
                ui.info(f"[DRY RUN] Would remove backup: {backup}")
                results.append(
                    {"name": "backup", "status": "skipped", "detail": backup}
                )
            else:
                shutil.rmtree(backup)
                ui.success(f"Removed backup: {backup}")
                results.append({"name": "backup", "status": "ok", "detail": backup})
                if audit_log:
                    audit_log.record_file(
                        backup, "delete", "ok", "backup removed by uninstall"
                    )

    return results


def _remove_launcher_and_install_dir(
    remove_install_dir=False, dry_run=False, audit_log=None
):
    results = []
    if os.path.lexists(DEFAULT_LAUNCHER):
        if dry_run:
            ui.info(f"[DRY RUN] Would remove launcher: {DEFAULT_LAUNCHER}")
            results.append(
                {"name": "launcher", "status": "skipped", "detail": "dry run"}
            )
        else:
            remove_path_safe(DEFAULT_LAUNCHER)
            ui.success(f"Removed launcher: {DEFAULT_LAUNCHER}")
            results.append({"name": "launcher", "status": "ok", "detail": "removed"})
            if audit_log:
                audit_log.record_file(
                    DEFAULT_LAUNCHER, "delete", "ok", "launcher removed"
                )

    if remove_install_dir and os.path.isdir(DEFAULT_INSTALL_DIR):
        if dry_run:
            ui.info(f"[DRY RUN] Would remove install dir: {DEFAULT_INSTALL_DIR}")
            results.append(
                {"name": "install_dir", "status": "skipped", "detail": "dry run"}
            )
        else:
            remove_path_safe(DEFAULT_INSTALL_DIR)
            ui.success(f"Removed install dir: {DEFAULT_INSTALL_DIR}")
            results.append({"name": "install_dir", "status": "ok", "detail": "removed"})

    return results


def cmd_uninstall(args):
    """Remove deployed files and optionally dependencies."""
    ui.banner()
    env = detect()

    ui.header("Uninstall MPV Auto-Deploy")

    # Load the audit log to find out which packages were pre-existing.
    # If no log exists we fall back to the safe default (assume everything
    # is pre-existing so nothing is auto-removed).
    audit_log = _audit_log_for(env)
    pre_existing_pkgs = audit_log.get_pre_existing_packages()

    if not pre_existing_pkgs:
        ui.warn("No audit log found — all packages assumed pre-existing.")
        ui.warn(
            "System packages will NOT be auto-removed even if --remove-deps is set."
        )

    # Build and show the full uninstall plan so the user can review what
    # will actually happen before anything is deleted.
    plan = build_uninstall_plan(
        env,
        pre_existing_pkgs=pre_existing_pkgs,
        purge_config=args.purge_config,
        remove_backups=args.remove_backups,
        remove_deps=args.remove_deps,
        remove_python=getattr(args, "remove_python", False),
    )
    display_plan(plan, "Uninstall Plan")

    # Ask for a single confirmation that covers everything.
    if not args.dry_run:
        if not confirm_plan(plan, "uninstall"):
            ui.warn("Uninstall cancelled by user.")
            return

    if _is_dry_run(args):
        remove_results = _remove_deployed_files(
            env,
            purge_config=args.purge_config,
            remove_backups=args.remove_backups,
            dry_run=True,
            audit_log=None,
        )
        dep_results = []
        if args.remove_deps:
            dep_results = uninstall_deps(
                env,
                remove_python=getattr(args, "remove_python", False),
                dry_run=True,
                pre_existing_pkgs=pre_existing_pkgs,
                audit_log=None,
            )
        else:
            dep_results.append(
                {"name": "dependencies", "status": "skipped", "detail": "not requested"}
            )
        cleanup_results = _remove_launcher_and_install_dir(
            remove_install_dir=args.remove_install_dir,
            dry_run=True,
            audit_log=None,
        )
        ui.summary(remove_results + dep_results + cleanup_results)
        return

    with _operation_lock(env.config_dir):
        if args.purge_config:
            audit_log = AuditLog(tx.canonical(env.config_dir) + ".uninstall-audit.json")
        audit_log.start_session("uninstall", env)
        try:
            # Keep a safety snapshot unless explicitly removing backups too.
            if not args.remove_backups:
                backup_existing(env.config_dir, audit_log=audit_log)
            remove_results = _remove_deployed_files(
                env, purge_config=args.purge_config, remove_backups=args.remove_backups,
                dry_run=False, audit_log=audit_log,
            )
            dep_results = []
            if args.remove_deps:
                dep_results = uninstall_deps(
                    env, remove_python=getattr(args, "remove_python", False),
                    dry_run=False, pre_existing_pkgs=pre_existing_pkgs, audit_log=audit_log,
                )
            cleanup_results = _remove_launcher_and_install_dir(
                remove_install_dir=args.remove_install_dir, dry_run=False, audit_log=audit_log,
            )
            all_results = remove_results + dep_results + cleanup_results
            ui.summary(all_results)
            if any(result.get("status") == "failed" for result in all_results):
                raise RuntimeError("Uninstall completed with failures")
            audit_log.complete_session("completed")
            ui.panel("Uninstall completed.", title="Success", style="green")
        except BaseException:
            audit_log.complete_session("failed")
            raise


def _is_interactive_session():
    return hasattr(sys.stdin, "isatty") and sys.stdin.isatty()


def _has_explicit_action(args):
    return any(
        [
            args.install,
            args.update,
            args.verify,
            args.status,
            args.rollback is not None,
            args.uninstall,
            args.migrate_from_old,
            getattr(args, "sync_deps", False),
        ]
    )


def _interactive_menu(args):
    ui.banner()
    menu_text = (
        "  [cyan]1)[/cyan] Full install  [dim]detect → deps → fetch → deploy → verify[/dim]\n"
        "  [cyan]2)[/cyan] Update scripts/shaders  [dim]re-fetch and deploy latest versions[/dim]\n"
        "  [cyan]3)[/cyan] Rollback (latest backup)  [dim]restore config to previous state[/dim]\n"
        "  [cyan]4)[/cyan] Rollback (specific backup path)  [dim]restore config from specific path[/dim]\n"
        "  [cyan]5)[/cyan] Verify installation  [dim]run self-diagnostic checks[/dim]\n"
        "  [cyan]6)[/cyan] Show status  [dim]list installed script and shader versions[/dim]\n"
        "  [cyan]7)[/cyan] Uninstall deployed files  [dim]remove MPV files deployed by this tool[/dim]\n"
        f"  [cyan]{MENU_MAX_OPTION})[/cyan] Full remove  [dim]uninstall files + backups + deps + install dir[/dim]\n"
        "  [cyan]0)[/cyan] Exit  [dim]quit without doing anything[/dim]"
    )
    ui.panel(menu_text, title="Main Menu", style="blue")

    choices = [str(i) for i in range(MENU_MAX_OPTION + 1)]
    choice = ui.ask_choice("Select option", choices=choices)

    if choice == "1":
        args.install = True
    elif choice == "2":
        args.update = True
    elif choice == "3":
        args.rollback = LATEST_BACKUP_SENTINEL
    elif choice == "4":
        path = input("  Backup path: ").strip()
        if not path:
            raise ValueError("Backup path cannot be empty. Please enter a valid path.")
        args.rollback = path
    elif choice == "5":
        args.verify = True
    elif choice == "6":
        args.status = True
    elif choice == "7":
        args.uninstall = True
        args.purge_config = ui.confirm("[red]Remove whole mpv config directory?[/red]")
        args.remove_backups = ui.confirm("[red]Remove rollback backups too?[/red]")
    elif choice == str(MENU_MAX_OPTION):
        args.uninstall = True
        args.purge_config = True
        args.remove_backups = True
        args.remove_deps = True
        args.remove_install_dir = True
        ui.warn(
            "Removing Python packages is potentially risky: other tools on your system may depend on the same packages."
        )
        ui.info(
            "The audit log will be consulted — only packages installed by this tool will be removed."
        )
        args.remove_python = ui.confirm(
            "[red]Also remove Python packages installed by this tool?[/red]"
        )
    elif choice == "0":
        raise KeyboardInterrupt


def main():
    parser = argparse.ArgumentParser(
        description="MPV Auto-Deploy System — one command, full setup.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--install",
        action="store_true",
        help="Full install (detect → deps → fetch → deploy → verify)",
    )
    parser.add_argument(
        "--update", action="store_true", help="Update scripts/shaders only"
    )
    parser.add_argument(
        "--rollback",
        nargs="?",
        const=LATEST_BACKUP_SENTINEL,
        metavar="BACKUP_DIR",
        help="Rollback to latest backup (or provide a specific backup directory)",
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="Remove deployed files/config by this installer",
    )
    parser.add_argument(
        "--verify", action="store_true", help="Verify current deployment"
    )
    parser.add_argument("--status", action="store_true", help="Show installed versions")
    parser.add_argument(
        "--interactive", action="store_true", help="Show interactive menu"
    )
    parser.add_argument(
        "--migrate-from-old",
        action="store_true",
        help="Generate non-destructive migration candidates for review",
    )
    parser.add_argument(
        "--purge-config",
        action="store_true",
        help="With --uninstall: remove full mpv config directory",
    )
    parser.add_argument(
        "--remove-backups",
        action="store_true",
        help="With --uninstall: remove backup directories",
    )
    parser.add_argument(
        "--remove-deps",
        action="store_true",
        help="With --uninstall: uninstall managed dependencies",
    )
    parser.add_argument(
        "--remove-python",
        action="store_true",
        help="With --remove-deps: also try uninstalling python package",
    )
    parser.add_argument(
        "--remove-install-dir",
        action="store_true",
        help="With --uninstall: remove ~/.mpv-deploy and launcher",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Preview without making changes"
    )
    parser.add_argument(
        "--mpv-profile",
        choices=sorted(MPV_EXPERIENCE_PROFILES.keys()),
        default=MPV_PROFILE_DEFAULT,
        help="mpv behavior profile: 'windows-like' (default unified experience) or 'native' (platform-specific behavior)",
    )
    parser.add_argument(
        "--anime-preset",
        choices=["fast", "A", "A+A", "B", "C", "off"],
        default="A+A",
        help="Anime4K shader chain preset (default: A+A)",
    )
    parser.add_argument(
        "--scaler-tier",
        choices=["light", "balanced", "quality"],
        default="quality",
        help="Scaler tier for upscaling quality (default: quality)",
    )
    parser.add_argument(
        "--display-mode",
        choices=["auto", "fixed", "vrr"],
        default="fixed",
        help="Display sync mode: fixed (default), vrr, or auto (alias of fixed; vrr requires explicit opt-in)",
    )
    parser.add_argument(
        "--dither-depth",
        choices=["auto", "8", "10"],
        default="auto",
        help="Dither depth: mpv auto (default), or explicit 8/10 bits",
    )
    parser.add_argument(
        "--mpv-version",
        metavar="TAG",
        default=None,
        help="Override pinned mpv Windows build tag (e.g. 2025-01-15)",
    )
    parser.add_argument(
        "--sync-deps",
        action="store_true",
        help="Automated dependency provisioning (yt-dlp, ffmpeg-full, alass, ffsubsync)",
    )

    args = parser.parse_args()

    try:
        if args.interactive or (
            not _has_explicit_action(args) and _is_interactive_session()
        ):
            _interactive_menu(args)

        # Default to --install if no action specified and not interactive
        if not _has_explicit_action(args):
            args.install = True

        if args.migrate_from_old:
            cmd_migrate(args)
        elif args.rollback is not None:
            cmd_rollback(args)
        elif args.uninstall:
            cmd_uninstall(args)
        elif args.verify:
            cmd_verify(args)
        elif args.status:
            cmd_status(args)
        elif args.update:
            cmd_update(args)
        elif args.sync_deps:
            cmd_sync_deps(args)
        else:
            cmd_install(args)
    except KeyboardInterrupt:
        ui.warn("Interrupted by user.")
        sys.exit(130)
    except Exception as e:
        ui.error(f"Fatal error: {e}")
        if os.getenv("DEBUG"):
            raise
        sys.exit(1)


if __name__ == "__main__":
    main()
